spring:
  datasource:
    url: jdbc:h2:file:./h2/db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2_console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2

server:
  error:
    include-message: always

partner-service:
  instrument-stream-url: ws://localhost:8032/instruments
  quote-stream-url: ws://localhost:8032/quotes

